### PR TITLE
Fixing build action

### PR DESCRIPTION
**Pull request by camjac251**
I think this should fix it, maybe

### CODE REVIEW

**Comment by theChaosCoder** [comment]
wheel is needed for upx?

**Comment by camjac251** [comment]
Wheel isn't needed but it was giving errors so maybe it could help, not sure

**Comment by theChaosCoder** [comment]
We'll see in a bit :)

**Comment by camjac251** [comment]
I made another error :/
Win32 works but Win64 is given 32-bit as well...

**Comment by camjac251** [comment]
I don't want to clutter up these pull requests. It's a simple fix if you can do it, on line 72, change win32 to win64

**Comment by theChaosCoder** [comment]
The upx build is not working. And that is why pyinstaller did not work for me locally . No problems without upx.

**Pull request merged**
