### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by camjac251**
I noticed that there were still references to Vapoursynth so hopefully this fixes it all while still working. More info in commit comment

### CODE REVIEW

**Comment by theChaosCoder** [comment]
Avi* does not sound right to me.
I would change it to AVSPlugin and AvsScript (or AvsiScript) maybe. I mean these are avs scripts and plugins, not avi scripts...

Why is local ignored?

**Comment by camjac251** [comment]
I avoided using AVSScript since it's a double S. I just took the Avi part of avisynth for the naming convention

**Comment by camjac251** [comment]
I made a mistake there adding `local` to `.gitignore`. I'll fix it and the naming part too

**Comment by theChaosCoder** [comment]
dlcache would make more sense :-)

**Comment by camjac251** [comment]
Ok how does this look. I did a few things. Renamed `Avi` to `avs` for the prefix of Plugins and Scripts. Also renamed the local folder to packages for easier access. I've tested updating the repo locally and it seems to work

**Comment by theChaosCoder** [comment]
Still not sure about the new types, but _"Names are sound and smoke"_ (Goethe's Faust) so who cares :D

**Comment by camjac251** [comment]
Just realized one more change I would've made to the readme. It mentions choosing architectures based on the installed python version.

**Comment by theChaosCoder** [comment]
and maybe avsrepo.py needs to be replaced with avsrepo.exe since 99% of avisynth users won't have python installed anyway.

**Comment by camjac251** [comment]
Ah that is true. Maybe it could be possible to also add to scoop :) for easy updates

**Pull request merged**
