### PR TITLE
Added UPX and icon

### PR DESCRIPTION
**Pull request by camjac251**
This should help with the UPX optimization. I also added a temporary icon for the app too.

I'm not sure this compiles or not. Can it be tested?

### CODE REVIEW

**Comment by camjac251** [comment]
Would it be possible to add a tag to the latest commit?

image

Nevermind it looks like you did :)

**Comment by theChaosCoder** [comment]
It seems upx was not detected 
`234 INFO: UPX is not available.`

**Comment by camjac251** [comment]
The icon might've increased the file size a bit. I packed in multiple resolutions to the icon using ImageMagick, which might be unnecessary for something like this.

**Comment by camjac251** [comment]
Oof, I'll take a look

**Comment by theChaosCoder** [comment]
The strange part is, I don't get the help text usage: avsrepo.exe blablazzz.exe [-h] [-f] [-p] [...
with the latest build. It seems PYTHONOPTIMIZE=1 is different then `python -O -m PyInstaller myscript.py` <-- this works locally with correct output

**Comment by camjac251** [comment]
It's because UPX is breaking some of the DLLs with its attempt to compress them. It might just be worth it to possibly optimize another way. 5MB for this small script does seem a bit too much. I'm attempting some fixes for UPX though

**Comment by theChaosCoder** [comment]
I thought that maybe -w was the problem. But nope, it was not.

**Pull request merged**
